name: Dependabot

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: npm update

      - run: npm audit fix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            This PR updates dependencies to their latest versions.

            - Updated npm packages
            - Fixed security vulnerabilities
            - Updated lock file
          branch: dependabot/update-dependencies
